In [5]:
from os import environ

from python_sdk.client import PyRogii

project_name = 'nsapegin (ft)'
well_name = 'Lateral1'

pr = PyRogii(
    client_id=environ.get('CLIENT_ID'),
    client_secret=environ.get('CLIENT_SECRET'),
    project_name=project_name,
    solo_username=environ.get('SOLO_USERNAME'),
    solo_password=environ.get('SOLO_PASSWORD'),
    papi_domain_name=environ.get('PAPI_DOMAIN_NAME')
)


wells = pr.get_project_wells()
wells

,uuid,name,api,operator,xsrf_real,ysrf_real,kb,convergence,tie_in_tvd,tie_in_ns,tie_in_ew,azimuth,starred
0,b7adb45d-3303-4e8a-be5c-b4ae720c4d96,Lateral1,Lateral1_API,,500000.0,600000.00,120.0912,0.0,0.0,0.0,0.0,5.672320,{'target_line': '2bf53754-7d55-4437-af88-1c6df...
1,4bc26736-da96-48e5-8dce-68d855d529a5,Lateral2,Lateral2_API,,500523.7,600211.51,130.7592,0.0,0.0,0.0,0.0,5.689773,NaN

In [5]:
wells[['name', 'api']]

       name           api
0  Lateral1  Lateral1_API
1  Lateral2  Lateral2_API

In [13]:
# Well (in the python dictionary format)
well

{'uuid': 'b7adb45d-3303-4e8a-be5c-b4ae720c4d96',
 'name': 'Lateral1',
 'operator': '',
 'api': 'Lateral1_API',
 'xsrf': 500000.0,
 'ysrf': 600000.0,
 'kb': 393.99999999999994,
 'convergence': 0.0,
 'azimuth': 325.00000000002143,
 'tie_in_tvd': 0.0,
 'tie_in_ns': 0.0,
 'tie_in_ew': 0.0}

In [6]:
well_trajectory = pr.get_well_trajectory(well_name=well_name)
well_trajectory

         azim      incl         md
0    0.000000  0.000000     0.0000
1    4.324926  0.006981   136.5504
2    0.000000  0.001745   152.4000
3    4.569272  0.005236   183.1848
4    5.180137  0.010472   258.1656
..        ...       ...        ...
164  5.588544  1.574287  5030.4192
165  5.607743  1.572542  5059.0704
166  5.614724  1.562070  5087.7216
167  5.619960  1.551598  5116.6776
168  5.619960  1.551598  5137.0992

[169 rows x 3 columns]

In [14]:
starred_interpretation = pr.get_well_starred_interpretation(well_name=well_name)
# Starred interpretation (python dictionary of three items (one python dict and two pandas dataframes))
starred_interpretation['meta']

{'name': 'Interpretation1',
 'properties': {'cutoff': {'val': 0},
  'palette': 10,
  'lightness': 0,
  'transparency': 0,
  'typelogFillUuid': '4fd4b926-9660-481f-aa0b-862dbde49217',
  'extensionGridUuid': '00000000-0000-0000-0000-000000000000',
  'faultLabelVisible': True,
  'reverse_extension': False,
  'zero_horizon_uuid': '00000000-0000-0000-0000-000000000000',
  'coloredLogsVisible': True,
  'boundaryPointsColor': '#ffa5a5a5',
  'interpretationExtend': {'val': 0},
  'boundaryPointsVisible': True,
  'display_hidden_segment': True},
 'owner': 1102,
 'mode': 'PUBLIC',
 'uuid': '4e1fd6d7-8651-4835-b0b3-347239f2e84c'}

In [8]:
starred_interpretation['horizons']

,3ae7c307-2333-4a73-b3d0-b151bfbfbb22,7b05d3aa-9398-4708-b465-d60ec6b58478,edfe0eda-3ccd-4673-b005-a0bd32b3c1d0,f615f32b-fb58-471e-8fdb-469f3a2d6ef9
tvd,3571.936803,3510.638475,3561.991179,3544.007979
uuid,3ae7c307-2333-4a73-b3d0-b151bfbfbb22,7b05d3aa-9398-4708-b465-d60ec6b58478,edfe0eda-3ccd-4673-b005-a0bd32b3c1d0,f615f32b-fb58-471e-8fdb-469f3a2d6ef9
name,Base_Res horizon,Top_Res horizon,Base_Trgt horizon,Top_Trgt horizon

In [22]:
starred_interpretation['segments']

,boundary_type,end,horizon_shifts,md,start,uuid
0,1,-2.001224,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,3439.650526,0.000000,dc958191-5835-4f48-865d-0333c676de1f
1,1,-5.764493,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,3508.552800,-2.001230,695cd224-098e-486c-9ffe-64e7010003ca
2,1,-10.215713,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,3537.508800,-5.764491,420a7507-fd80-4d3a-9c3c-ac404c9a3c65
3,1,-19.017023,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,3714.292800,-10.215713,657b6d22-e11c-49d5-a5d6-da031d9d063d
4,1,0.000000,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,3979.684251,0.000000,4cb80808-236a-43db-838c-7bde13fd6749
5,0,-18.103030,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4084.549663,-15.178863,f8d04675-fba2-494b-b983-7b4808dcd6d6
6,1,0.000000,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4221.449520,0.000000,fc22733a-96f5-485a-b806-b16b696ba1ce
7,0,-33.715135,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4264.277649,-31.497925,84a9ba6d-a2c8-4789-babd-98e935a06e8c
8,1,0.000000,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4313.438160,0.000000,d8b353ee-5950-45ef-b5b2-6bab6899a6f7
9,1,-36.161666,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4340.504400,-33.715158,0401aceb-0a40-46f5-92dc-576f84e68335
10,1,-42.999488,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4409.236800,-36.161586,802003ad-c638-4614-86bc-9059ff72055c
11,1,0.000000,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4439.521728,0.000000,980eb924-c8e4-4dc7-8403-1b4f4a7bf37e
12,0,-64.208829,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4451.760553,-65.526535,2c77776e-8004-4a09-a32c-4f79d29baec9
13,1,0.000000,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4509.717168,0.000000,0dc2516b-9da7-43d2-baca-da6cfb0b7654
14,1,0.000000,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4564.727472,0.000000,c81a0581-717a-4b05-bbdf-b0068424eac0
15,1,0.000000,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4646.203560,0.000000,ae3e36c9-311d-41ca-b787-ed6098daf03a
16,1,0.000000,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4724.994360,0.000000,52272f89-99c8-46c3-8d48-d689aab5fe7a
17,1,-71.888414,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4758.898179,-70.024683,279f1fc2-ce6e-401a-9fea-a4953a7c05b3
18,1,-77.615386,{'3ae7c307-2333-4a73-b3d0-b151bfbfbb22': {'end...,4866.894000,-71.880616,bff2b18b-45a6-47a7-862f-921083ad767a

In [11]:
starred_targetline = pr.get_well_starred_target_line(well_name=well_name)
starred_targetline

{'azimuth': 324.9999999999999,
 'delta_tvd': 19.46959181839702,
 'delta_vs': 3377.727551431245,
 'inclination': 89.66974450459126,
 'length': 3377.783663395759,
 'name': 'Target Line1',
 'origin_base_corridor_tvd': None,
 'origin_md': None,
 'origin_top_corridor_tvd': None,
 'origin_tvd': 11488.203352355784,
 'origin_vs': 6044.52554257121,
 'origin_x': 496536.37744074466,
 'origin_y': 604953.7485579867,
 'origin_z': -11094.203352355784,
 'target_base_corridor_tvd': None,
 'target_md': None,
 'target_top_corridor_tvd': None,
 'target_tvd': 11507.67294417418,
 'target_vs': 9422.253094002455,
 'target_x': 494598.99250883,
 'target_y': 607720.6209867928,
 'target_z': -11113.67294417418,
 'tvd_vs': 11453.362044625126,
 'uuid': '2bf53754-7d55-4437-af88-1c6dffdcd3e8'}

In [12]:
import random
nested_well_name = 'Nested Well ' + str(random.randint(0, 10000))
result = pr.create_nested_well(
    well_name=well_name,
    nested_well_name=nested_well_name,
    operator='Operator',
    api=nested_well_name,
    xsrf=100000.0,
    ysrf=100000.0,
    kb=0.0,
    tie_in_tvd=0.0,
    tie_in_ns=0.0,
    tie_in_ew=0.0,
)
print(f'Created nested well "{nested_well_name}"')

Created nested well "Nested Well 1154"